{{- if index .Values "mariadb-cluster" "enabled" }}
apiVersion: v1
kind: Secret
metadata:
  name: mariadb
type: Opaque
stringData:
  password: {{ index .Values "mariadb-cluster" "auth" "password" | quote }}
  root-password: {{ index .Values "mariadb-cluster" "auth" "rootPassword" | quote }}
{{ end }}