quarkus:
  live-reload:
    instrumentation: true
  http:
    host: 0.0.0.0
    cors: false
  log:
    category:
      esthesis:
        level: DEBUG
esthesis:
  edge:
    modules:
      enedis:
        self-registration:
          state-checking: false

"%debug-rest":
  quarkus:
    log:
      category:
        "org.jboss.resteasy":
          min-level: TRACE
          level: TRACE
    rest-client:
      logging:
        scope: request-response
        body-limit: 65536
