quarkus:
  banner:
    enabled: false
  hibernate-orm:
    database:
      generation: update
  datasource:
    db-kind: mariadb
    username: esthesis-system
    password: esthesis-system
    jdbc:
      url: jdbc:mariadb://localhost:4306/esthesis-edge
  liquibase:
    change-log: db/changeLog.xml
    migrate-at-start: true
  rest-client:
    EsthesisAgentServiceClient:
      url: "${QUARKUS_REST_CLIENT_ESTHESIS_AGENT_SERVICE_CLIENT_URL:http://localhost:59070}"
      scope: Singleton
    EnedisClient:
      url: "${QUARKUS_REST_CLIENT_ENEDIS_CLIENT_URL:https://gw.ext.prod-sandbox.api.enedis.fr}"
      scope: Singleton
  log:
    min-level: TRACE
    category:
      esthesis:
        min-level: TRACE
  swagger-ui:
    always-include: true
    path: /api/openapi-ui
    title: esthesis EDGE API
    operations-sorter: alpha
    tags-sorter: alpha
    default-models-expand-depth: -1
  smallrye-openapi:
    path: /api/openapi
    security-scheme: api-key
    security-scheme-name: X-ESTHESIS-EDGE-ADMIN-SECRET
    api-key-parameter-in: header
    api-key-parameter-name: X-ESTHESIS-EDGE-ADMIN-SECRET

# noinspection YAMLSchemaValidation
esthesis:
  edge:
    admin-secret: ca820829-328f-41e0-9207-ef42372f94c3
    sync-cron: "0 0 * * * ?"
    purge-cron: "0 0 0 * * ?"
    purge-successful-minutes: 60
    purge-queued-minutes: 10080
    local:
      enabled: false
      influx-db:
        url: http://localhost:9086
        token: esthesis-edge
        bucket: edge
        org: esthesis
    core:
      push:
        enabled: false
        url: ssl://mosquitto.esthesis:8883
        topic-telemetry: esthesis/telemetry
        topic-ping: esthesis/ping
      registration:
        enabled: false
        secret:
        cron: "0 0 * * * ?"
      tags:
        - edge
      key-algorithm: RSA
      cert: "<base64 cert>"
    modules:
      enedis:
        enabled: false
        cron: "0 0 6 * * ?"
        max-devices: 1000
        past-days-init: 30
        client-id: esthesis-edge
        client-secret: esthesis-edge
        fetch-types:
          dc:
            enabled: true
            category: "energy"
            measurement: "dc"
            errors-threshold: 10
          dcmp:
            enabled: true
            category: "energy"
            measurement: "dcmp"
            errors-threshold: 10
          dp:
            enabled: true
            category: "energy"
            measurement: "dp"
            errors-threshold: 10
        self-registration:
          enabled: true
          state-checking: true
          welcome-url:
          redirect-url: http://localhost:8080
          duration: P1Y
          page:
            logo1-url: https://datahub-enedis.fr/wp-content/uploads/Enedis-signature_couleur_RVB_72-dpi.png
            logo1-alt: Enedis
            logo2-url: https://www.eurodyn.com/wp-content/uploads/2018/11/logo_ed.png
            logo2-alt: European Dynamics
            logo3-url: https://esthes.is/docs/edge/images/logo.png
            logo3-alt: esthesis EDGE
            button-url: https://datahub-enedis.fr/wp-content/uploads/2018/11/vert-enedis.png
            registration:
              title: "Connect your Enedis account"
              message: "You will be redirected to Enedis, where you have to authenticate with your
                Enedis account, and authorise this application to retrieve your electricity consumption
                data. The authorisation will be valid for 1 year. Your data will be used by us to provide
                you with insights and recommendations on how to save energy."
            success:
              title: "Account connected"
              message: "Your account was successfully connected, you may now close this window."
            error:
              title: "Error connecting account"
              message: "An error occurred while connecting your account. Please try again later."
