quarkus:
  scheduler:
    enabled: false
  datasource:
    db-kind: h2
    jdbc:
      url: jdbc:h2:mem:;DATABASE_TO_UPPER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;
  rest-client:
    EsthesisAgentServiceClient:
      scope: ApplicationScoped
    EnedisClient:
      scope: ApplicationScoped
  liquibase:
    enabled: false

esthesis:
  edge:
    core:
      registration:
        secret: "test"
        enabled: true
    modules:
      enedis:
        enabled: true
        self-registration:
          state-checking: false
