quarkus:
  banner:
    enabled: false
  hibernate-orm:
    database:
      generation: update
  datasource:
    db-kind: mariadb
    username: esthesis-system
    password: esthesis-system
    jdbc:
      url: jdbc:mariadb://localhost:4306/esthesis-edge
  rest-client:
    EsthesisAgentServiceClient:
      url: http://localhost:59070
      scope: Singleton
    EnedisClient:
      url: https://ext.prod-sandbox.api.enedis.fr
      scope: Singleton

# noinspection YAMLSchemaValidation
esthesis:
  edge:
    admin-secret: ca820829-328f-41e0-9207-ef42372f94c3
    sync-cron: "0 0 * * * ?"
    purge-cron: "0 0 0 * * ?"
    purge-successful-minutes: 60
    purge-queued-minutes: 10080
    local:
      enabled: false
      influx-db:
        url: http://localhost:9086
        token: esthesis-edge
        bucket: edge
        org: esthesis
    core:
      push:
        enabled: false
        url: ssl://mosquitto.esthesis:8883
        topic-telemetry: esthesis/telemetry
        topic-ping: esthesis/ping
      registration:
        enabled: false
        secret:
      tags:
        - edge
      key-algorithm: RSA
    modules:
      enedis:
        enabled: false
        cron: "0 0 6 * * ?"
        max-devices: 1000
        past-days-init: 7
        client-id: myclientid
        client-secret: myclientsecret
        fetch-types:
          dc:
            enabled: true
            category: "energy"
            measurement: "dc"
            errors-threshold: 3
          dcmp:
            enabled: true
            category: "energy"
            measurement: "dcmp"
            errors-threshold: 3
          dp:
            enabled: true
            category: "energy"
            measurement: "dp"
            errors-threshold: 3
        self-registration:
          enabled: true
          state-checking: false
          welcome-url:
          redirect-url: http://localhost:8080
          duration: P1Y
          page:
            logo1-url: https://getlogovector.com/wp-content/uploads/2019/08/enedis-logo-vector.png
            logo1-alt:
            logo2-url:
            logo2-alt:
            registration:
              title: "Connect your Enedis account"
              message: "You will be redirected to Enedis, where you have to authenticate with your
                Enedis account, and authorise this application to retrieve your electricity consumption
                data. The authorisation will be valid for 1 year. Your data will be used by us to provide
                you with insights and recommendations on how to save energy."
            success:
              title: "Account connected"
              message: "Your account was successfully connected, you may now close this window."
            error:
              title: "Error connecting account"
              message: "An error occurred while connecting your account. Please try again later."
