apiVersion: v2
name: esthesis-edge-helm
home: https://esthes.is
sources:
  - https://github.com/esthesis-iot
maintainers:
  - name: European Dynamics SA
    email: esthesis@eurodyn.com
    url: https://www.eurodyn.com
icon: https://esthes.is/media/logo.png
version: "1.0.21-SNAPSHOT"
appVersion: "1.0.21-SNAPSHOT"
dependencies:
  - name: mariadb-cluster
    version: "25.8.3"
    repository: "https://github.com/mariadb-operator/mariadb-operator/deploy/charts"
    condition: mariadb-cluster.enabled
  - name: mariadb-operator
    version: "25.8.3"
    repository: "https://github.com/mariadb-operator/mariadb-operator/deploy/charts"
    condition: mariadb-operator.enabled
  - name: mariadb-operator-crds
    version: "25.8.3"
    repository: "https://github.com/mariadb-operator/mariadb-operator/deploy/charts"
    condition: mariadb-operator-crds.enabled
  - name: influxdb2
    version: "2.1.2"
    repository: "https://helm.influxdata.com"
    condition: influxdb2.enabled
