apiVersion: v2
name: esthesis-edge-helm
home: https://esthes.is
sources:
  - https://github.com/esthesis-iot
maintainers:
  - name: European Dynamics SA
    email: esthesis@eurodyn.com
    url: https://www.eurodyn.com
icon: https://esthes.is/media/logo.png
version: "1.0.21-SNAPSHOT"
appVersion: "1.0.21-SNAPSHOT"
dependencies:
  # If you wish to install mariadb via the operator you will first to install the mariadb-operator-crds chart:
  # helm repo add mariadb-operator https://helm.mariadb.com/mariadb-operator
  # helm install mariadb-operator-crds mariadb-operator/mariadb-operator-crds
  - name: mariadb-operator
    version: "25.8.3"
    repository: "https://helm.mariadb.com/mariadb-operator"
    condition: mariadb-operator.enabled
  - name: mariadb-cluster
    version: "25.8.3"
    repository: "https://helm.mariadb.com/mariadb-operator"
    condition: mariadb-cluster.enabled
  - name: influxdb2
    version: "2.1.2"
    repository: "https://helm.influxdata.com"
    condition: influxdb2.enabled
