global:
  # -- The secret used to pull images from the container registry.
  imagePullSecrets:
  # -- The storage class used by the persistent volume claims.
  storageClass:
  # -- A custom registry to fetch container images from, in the form of "registry/project", e.g. "192.168.50.211:5000/esthesis"
  esthesisRegistry:
  # -- The timezone used by the application.
  timezone: "Europe/Athens"

quarkus:
  datasource:
    # -- The username of MariaDB used by esthesis EDGE.
    username: "esthesis-system"
    # -- The password of MariaDB used by esthesis EDGE.
    password: "esthesis-system"
    jdbc:
      # -- The JDBC URL of MariaDB used by esthesis EDGE.
      url: "jdbc:mariadb://esthesis-edge-mariadb:3306/esthesis-edge"
  restClient:
    # -- The URL of the esthesis Agent Service.
    esthesisAgentServiceClient:
      url: "http://esthesis-agent-service:8080"
    # -- The URL of the Enedis API.
    enedisClient:
      url: "https://gw.ext.prod-sandbox.api.enedis.fr"
    # -- The URL of the Fronius Solar API.
    froniusClient:
      url: "http://localhost:8080/solar_api"
    # -- The URL of the DEDDIE API.
    deddieClient:
        url: "https://apps.deddie.gr/mdp/rest"
  log:
    level: "INFO"

esthesis:
  edge:
    # -- The secret used to access the admin API of esthesis EDGE.
    adminSecret: "ca820829-328f-41e0-9207-ef42372f94c3"
    # -- The cron expression used to schedule how often new data is fetched.
    syncCron: "0 0 * * * ?"
    # -- The cron expression used to schedule how often data is purged.
    purgeCron: "0 0 0 * * ?"
    # -- The number of minutes after which data successfully stored in local database or esthesis CORE is purged from the queue.
    purgeSuccessfulMinutes: 60
    # -- The number of minutes after which data is purged from the queue, irrespective of its status.
    purgeQueuedMinutes: 10080
    service:
      # -- The type of the service to be created for esthesis EDGE.
      type: ClusterIP
      # -- The port of the service to be created for esthesis EDGE.
      port: 80
    ingress:
      # -- Whether an ingress resource is created for esthesis EDGE.
      enabled: false
      # -- The name of the cluster issuer used by cert-manager for the ingress resource.
      certManagerClusterIssuer:
      # -- The name of the issuer used by cert-manager for the ingress resource.
      certManagerIssuer:
      # -- The class name of the ingress controller.
      className:
      # -- The hostname of the ingress resource.
      hostname:
      # -- The name of the Kubernetes TLS secret that contains the TLS certificate and private key for securing the Ingress with HTTPS.
      ingressTlsSecret:
    local:
      # -- Whether the local InfluxDB database is updated with data fetched.
      enabled: false
      influxDb:
        # -- The URL of the local InfluxDB database.
        url: "http://esthesis-edge-influxdb:8088"
        # -- The token used to access the local InfluxDB database.
        token: "fVfC4PNVzPnO_qsYY4X3lsvYmqIZNFHE3kE6fI8hpZqR"
        # -- The bucket used to store data in the local InfluxDB database.
        bucket: "edge"
        # -- The organisation used to store data in the local InfluxDB database.
        org: "esthesis"
    core:
      push:
        # -- Whether data is pushed to esthesis CORE.
        enabled: false
        # -- The URL of the esthesis CORE MQTT broker.
        url: "ssl://mosquitto.esthesis:8883"
        # -- The topic used to send telemetry data to esthesis CORE.
        topicTelemetry: "esthesis/telemetry"
        # -- The topic used to send ping data to esthesis CORE.
        topicPing: "esthesis/ping"
      registration:
        # -- Whether device registration in esthesis CORE takes place when a new device is registered in esthesis EDGE.
        enabled: false
        # -- The cron expression used to schedule how often new EDGE devices should be registered in esthesis CORE.
        cron: "0 0 * * * ?"
        # -- The secret used to access the registration API of esthesis CORE.
        secret: "esthesis-edge"
        # -- The tags added to an esthesis EDGE devices registered in esthesis CORE.
        tags:
          - edge
      # -- The algorithm used to generate keys for devices in esthesis CORE.
      keyAlgorithm: "RSA"
      # -- The certificate used by esthesis CORE MQTT server.
      cert: "<base64 cert>"
    modules:
      enedis:
        # -- Whether the Enedis module is enabled.
        enabled: false
        # -- The cron expression used to schedule how often data is fetched from Enedis.
        cron: "0 0 6 * * ?"
        # -- The maximum number of devices that can be registered by the Enedis module.
        maxDevices: 1000
        # -- The number of days in the past for which data is fetched from Enedis when a new device is registered.
        pastDaysInit: 30
        # -- The client ID used to access the Enedis API.
        clientId: myclientid
        # -- The client secret used to access the Enedis API.
        clientSecret: myclientsecret
        fetchTypes:
          dc:
            # -- Whether  Data Consumption data is fetched from Enedis.
            enabled: true
            # -- The category name used to store Data Consumption data (used both in local InfluxDB database and in eLP).
            category: "energy"
            # -- The measurement name used to store Data Consumption data (used both in local InfluxDB database and in eLP).
            measurement: "dc"
            # -- The number of errors after which the fetching of Data Consumption data is stopped.
            errorsThreshold: 10
          dcmp:
            # -- Whether Data Consumption Max Power data is fetched from Enedis.
            enabled: true
            # -- The category name used to store Data Consumption Max Power data (used both in local InfluxDB database and in eLP).
            category: "energy"
            # -- The measurement name used to store Data Consumption Max Power data (used both in local InfluxDB database and in eLP).
            measurement: "dcmp"
            # -- The number of errors after which the fetching of Data Consumption Max Power data is stopped.
            errorsThreshold: 10
          dp:
            # -- Whether Data Production data is fetched from Enedis.
            enabled: true
            # -- The category name used to store Data Production data (used both in local InfluxDB database and in eLP).
            category: "energy"
            # -- The measurement name used to store Data Production data (used both in local InfluxDB database and in eLP).
            measurement: "dp"
            # -- The number of errors after which the fetching of Data Production data is stopped.
            errorsThreshold: 10
          clc:
            # -- Whether  Consumption Load Curve data is fetched from Enedis.
            enabled: true
            # -- The category name used to store Consumption Load Curve data (used both in local InfluxDB database and in eLP).
            category: "energy"
            # -- The measurement name used to store Consumption Load Curve data (used both in local InfluxDB database and in eLP).
            measurement: "clc"
            # -- The number of errors after which the fetching of Consumption Load Curve data is stopped.
            errorsThreshold: 10
          plc:
            # -- Whether  Production Load Curve data is fetched from Enedis.
            enabled: true
            # -- The category name used to store Production Load Curve data (used both in local InfluxDB database and in eLP).
            category: "energy"
            # -- The measurement name used to store Production Load Curve data (used both in local InfluxDB database and in eLP).
            measurement: "plc"
            # -- The number of errors after which the fetching of Production Load Curve data is stopped.
            errorsThreshold: 10
        selfRegistration:
          # -- Whether the self-registration page and functionality is enabled for the Enedis module.
          enabled: false
          # -- Whether self-registration redirect from Enedis requires a valid state.
          stateChecking: false
          # -- The URL of the self-registration welcome page. If left empty, a default page is provided by the Enedis module.
          welcomeUrl:
          # -- The URL to which Enedis is redirecting the user after accepting access to their data.
          redirectUrl: http://localhost:8080
          # -- The duration for which the Enedis data access token is requested for (see Enedis API for details).
          duration: P1Y
          page:
            # -- The URL of the first logo being displayed on the self-registration page, if the welcome URL is empty.
            logo1Url:
            # -- The alt text of the first logo being displayed on the self-registration page, if the welcome URL is empty.
            logo1Alt:
            # -- The URL of the second logo being displayed on the self-registration page, if the welcome URL is empty.
            logo2Url:
            # -- The alt text of the second logo being displayed on the self-registration page, if the welcome URL is empty.
            logo2Alt:
            # -- The URL of the third logo being displayed on the self-registration page, if the welcome URL is empty.
            logo3Url:
            # -- The alt text of the third logo being displayed on the self-registration page, if the welcome URL is empty.
            logo3Alt:
            # -- The URL of the Enedis forward-button being displayed on the self-registration page.
            buttonUrl: https://datahub-enedis.fr/wp-content/uploads/2018/11/vert-enedis.png
            registration:
              # -- The title of the self-registration page, if the welcome URL is empty.
              title: "Connect your Enedis account"
              # -- The message displayed on the self-registration page, if the welcome URL is empty.
              message:
                "You will be redirected to Enedis, where you have to authenticate with your
                Enedis account, and authorise this application to retrieve your electricity consumption
                data. The authorisation will be valid for 1 year. Your data will be used by us to provide
                you with insights and recommendations on how to save energy."
            success:
              # -- The title of the success message displayed after a successful self-registration.
              title: "Account connected"
              # -- The message of the success message displayed after a successful self-registration.
              message: "Your account was successfully connected, you may now close this window."
            error:
              # -- The title of the error message displayed after an unsuccessful self-registration.
              title: "Error connecting account"
              # -- The message of the error message displayed after an unsuccessful self-registration.
              message: "An error occurred while connecting your account. Please try again later."

      fronius:
        # -- Whether the Fronius module is enabled.
        enabled: false
        # -- The cron expression used to schedule how often data is fetched from Fronius Solar API.
        cron: "0 0 6 * * ?"
        # -- The maximum number of devices that can be registered by the Fronius module.
        maxDevices: 1000
        fetchTypes:
          pfr:
            # -- Whether  Power Flow data is fetched from Fronius.
            enabled: true
            # -- The number of errors after which the fetching of Power Flow data is stopped.
            errorsThreshold: 10
            # -- Daily AC energy configuration.
            eday:
              # -- The category name used to store daily production data (used both in local InfluxDB database and in eLP).
              category: "energy"
              # -- The measurement name used to store daily production data (used both in local InfluxDB database and in eLP).
              measurement: "dailyProduction"

            # -- The hardware IDs of the inverters whose Power Flow data is fetched from Fronius.
            # -- The order of the inverters is important, as it should match the order of the inverters in the Fronius API response.
            invertersHardwareIds:
              - "fronius-pfr-inverter-0"

      deddie:
        # -- Whether the DEDDIE module is enabled.
        enabled: false
        # -- The cron expression used to schedule how often data is fetched from DEDDIE.
        cron: "0 0 6 * * ?"
        # -- The maximum number of devices that can be registered by the DEDDIE module.
        maxDevices: 1000
        # -- The number of days in the past for which data is fetched from DEDDIE when a new device is registered.
        pastDaysInit: 7
        fetchTypes:
          cac:
            # -- Whether Active Consumption data is fetched from DEDDIE.
            enabled: true
            # -- The category name used to store Active Consumption data (used both in local InfluxDB database and in eLP).
            category: "energy"
            # -- The measurement name used to store Active Consumption data (used both in local InfluxDB database and in eLP).
            measurement: "active"
            # -- The number of errors after which the fetching of Active Consumption data is stopped.
            errorsThreshold: 10
          crp:
            # -- Whether Reactive Power data is fetched from DEDDIE.
            enabled: true
            # -- The category name used to store Reactive Consumption data (used both in local InfluxDB database and in eLP).
            category: "energy"
            # -- The measurement name used to store Reactive Consumption data (used both in local InfluxDB database and in eLP).
            measurement: "reactive"
            # -- The number of errors after which the fetching of Reactive Consumption data is stopped.
            errorsThreshold: 10
          cep:
            # -- Whether Energy Produced data is fetched from DEDDIE.
            enabled: true
            # -- The category name used to store Energy Produced data (used both in local InfluxDB database and in eLP).
            category: "energy"
            # -- The measurement name used to store Energy Produced data (used both in local InfluxDB database and in eLP).
            measurement: "produced"
            # -- The number of errors after which the fetching of Energy Produced data is stopped.
            errorsThreshold: 10
          cei:
            # -- Whether Energy Injected data is fetched from DEDDIE.
            enabled: true
            # -- The category name used to store Energy Injected data (used both in local InfluxDB database and in eLP).
            category: "energy"
            # -- The measurement name used to store Energy Injected data (used both in local InfluxDB database and in eLP).
            measurement: "injected"
            # -- The number of errors after which the fetching of Energy Injected data is stopped.
            errorsThreshold: 10
        selfRegistration:
          # -- Whether the self-registration page and functionality is enabled for the DEDDIE module.
          enabled: true
          page:
            # -- The URL of the first logo being displayed on the self-registration page.
            logo1Url: https://deddie.gr/images/svgs/deddie-el.svg
            # -- The alt text of the first logo being displayed on the self-registration page.
            logo1Alt: Deddie
            # -- The URL of the second logo being displayed on the self-registration page.
            logo2Url: https://www.eurodyn.com/wp-content/uploads/2018/11/logo_ed.png
            # -- The alt text of the second logo being displayed on the self-registration page.
            logo2Alt: European Dynamics
            # -- The URL of the third logo being displayed on the self-registration page.
            logo3Url: https://esthes.is/docs/edge/images/logo.png
            # -- The alt text of the third logo being displayed on the self-registration page.
            logo3Alt: esthesis EDGE
            registration:
              # -- The title of the self-registration page.
              title: "DEDDIE Data Registration"
              # -- The message displayed on the self-registration page.
              message:
                "Please provide your Tax Number and the Access Token obtained from DEDDIE's Metering Data Portal. 
                 Optionally, you may enter one or more Supply Numbers. If no Supply Numbers are provided, all supplies 
                 linked to your Tax Number will be retrieved."
              # -- The placeholder text for the Tax Number input field on the self-registration page.
              placeholderTaxNumber: "Tax Number (required)"
              # -- The placeholder text for the Access Token input field on the self-registration page.
              placeholderAccessToken: "Access Token (required)"
                # -- The placeholder text for the Supply Numbers input field on the self-registration page.
              placeholderSupplyNumber: "Supply Number (optional)"
            success:
              # -- The title of the success message displayed after a successful self-registration.
              title: "Registration Successful"
              # -- The message of the success message displayed after a successful self-registration.
              message: "Your information has been registered successfully. You may now close this window."
            error:
              # -- The title of the error message displayed after an unsuccessful self-registration.
              title: "Registration Failed"
              # -- The message of the error message displayed after an unsuccessful self-registration.
              message: "We were unable to complete your registration. Please verify the information provided and try again."



mariadb:
  # -- Whether MariaDB will be installed.
  enabled: true
  image: 
    repository: bitnamilegacy/mariadb
  auth:
    # -- The password for the root MariaDB user.
    rootPassword: "esthesis-system"
    # -- The name of the database that will be created for esthesis EDGE.
    database: "esthesis-edge"
    # -- The username of the database user that will be created for esthesis EDGE.
    username: "esthesis-system"
    # -- The password of the database user that will be created for esthesis EDGE.
    password: "esthesis-system"
  volumePermissions:
    image:
      repository: bitnamilegacy/bitnami-shell-archived
  metrics:
    image:
      repository: bitnamilegacy/mysqld-exporter

influxdb:
  # -- Whether InfluxDB will be installed.
  enabled: true
  image:
    repository: bitnamilegacy/influxdb
  auth:
    # -- Whether a user token will be created during deployment.
    createUserToken: true
    admin:
      # -- The username of the InfluxDB admin user.
      username: "esthesis-system"
      # -- The password of the InfluxDB admin user.
      password: "esthesis-system"
      # -- The token that will be created for InfluxDB.
      token: "fVfC4PNVzPnO_qsYY4X3lsvYmqIZNFHE3kE6fI8hpZqR"
    user:
      # -- The organisation name of the esthesis EDGE user for InfluxDB.
      org: "esthesis"
      # -- The bucket name of esthesis EDGE in InfluxDB.
      bucket: "edge"
      # -- The username of the esthesis EDGE user for InfluxDB.
      username: "esthesis-admin"
      # -- The password of the esthesis EDGE user for InfluxDB.
      password: "esthesis-admin"
  persistence:
    # -- The size of the persistent volume claim for InfluxDB.
    size: "32Gi"
  volumePermissions:
    image:
      repository: bitnamilegacy/bitnami-shell-archived
  backup:
    google:
      image:
        repository: bitnamilegacy/google-cloud-sdk
    azure:
      image:
        repository: bitnamilegacy/azure-cli
    aws:
      image:
        repository: bitnamilegacy/aws-cli
